#!/usr/bin/env bash

# Check if all 4 parameters are provided
if [ $# -ne 4 ];
then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Copy the file to the remote server using SCP
# Disable strict host key checking to avoid prompting for confirmation
# Use the provided SSH key for authentication
# Copy the file specified by the first parameter
# To the remote server's home directory
scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~/

# Check if the file transfer was successful
if [ $? -ne 0 ];
then
    echo "File transfer failed"
    exit 1
fi