#!/usr/bin/env bash

# Check if all 4 parameters are provided
if [ $# -lt 4 ];
then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

PATH_TO_FILE=$1
IP=$2
USERNAME=$3
PATH_TO_SSH_KEY=$4

# Copy the file to the remote server using SCP
scp -o "StrictHostKeyChecking=no" -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "$USERNAME"@"$IP":~/"

# Check if the file transfer was successful
if [ $? -eq 0 ];
then
    echo "File transfer successful to $USERNAME@$IP"
else
    echo "File transfer failed to $USERNAME@$IP"
fi