#!/usr/bin/env bash
# Update the package list and install Nginx
sudo apt-get update && sudo apt-get install -y nginx

# Allow HTTP traffic in the firewall
sudo ufw allow 'Nginx HTTP'

# Create a basic "Hello World!" HTML page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Check the Nginx configuration
sudo nginx -t

# Reload the Nginx service
sudo service nginx reload