#!/usr/bin/env bash
# Update the package manager and install Nginx

apt-get update
apt-get -y install nginx

# Allow HTTP traffic through the firewall
sudo ufw allow 'Nginx HTTP'

redirect="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/aabine permanent;"
sudo sed -i "s/server_name _;/$redirect/" /etc/nginx/sites-enabled/default

sudo nginx -t

sudo service nginx restart
