#!/usr/bin/env bash
# Update the package manager and install Nginx

apt-get update
apt-get -y install nginx

# Allow HTTP traffic through the firewall
sudo ufw allow 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html

redirect="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/aabine permanent;"
sudo sed -i "s/server_name _;/$redirect/" /etc/nginx/sites-enabled/default

new_404_page="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$new_404_page/" /etc/nginx/sites-enabled/default

sudo nginx -t

sudo service nginx restart