#!/usr/bin/env bash

# Update the system
apt-get -y update

# Install Nginx
apt-get -y install nginx

# Create a custom 404 error page
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html

# Add your GitHub username and custom header configuration to Nginx
github_username="YourGitHubUsername"
sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/$github_username permanent;\n\n\terror_page 404 \/custom_404.html;\n\tlocation = \/custom_404.html {\n\t\troot \/usr\/share\/nginx\/html;\n\t\tinternal;\n\t}/" /etc/nginx/sites-available/default
sed -i "s/include \/etc\/nginx\/sites-enabled\/\*;/include \/etc\/nginx\/sites-enabled\/\*;\n\tadd_header X-Served-By \"$HOSTNAME\";/" /etc/nginx/nginx.conf

# Start Nginx service
service nginx start
