#!/usr/bin/env bash
# Installs and setup haproxy

apt-get install -y software-properties-common haproxy=1.8.\* && add-apt-repository -y ppa:vbernat/haproxy-1.8 && apt-get -y update

echo "ENABLED=1" > /etc/default/haproxy

cat <<EOF > /etc/haproxy/haproxy.cfg
# Listen to web1 and web2 servers
listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server web-1 100.25.147.171:80 check
   server web-2 54.237.225.149:80 check
EOF

systemctl start haproxy