#!/usr/bin/env bash
#Write a Bash script that displays a list of currently running processes.
#Display all processes, for all users, including those which might not have a TTY.
#Display the PID, along with the process name, of each process.

ps -auxf
