#!/usr/bin/env bash
# Configure UFW to block all incoming traffic except specific ports
sudo apt install ufw
sed -i 's/IPV6=.*/IPV6=yes/' /etc/default/ufw

# Set the default incoming policy to deny
ufw default deny incoming
ufw default allow outgoing

# Allow SSH (port 22)
sudo ufw allow 22/tcp

# Allow HTTP (port 80)
sudo ufw allow 80/tcp

# Allow HTTPS (port 443)
sudo ufw allow 443/tcp

# Enable UFW
sudo ufw enable